version: '3.7'
services:
  travel-web:
    build: .
    image: travel-web
    container_name: travel-web
    ports:
      - "8800:80"
    restart: always
    networks:
      - default
      # - tunnel